const weatherDescKo = [
  { weatherId:  201, content: '가벼운 비를 동반한 천둥구름' },
  { weatherId:  200, content: '비를 동반한 천둥구름' },
  { weatherId: 202, content:'폭우를 동반한 천둥구름' },
  { weatherId: 210, content: '약한 천둥구름' },
  { weatherId: 211, content: '천둥구름' },
  { weatherId: 212, content: '강한 천둥구름' },
  { weatherId: 221, content: '불규칙적 천둥구름' },
  { weatherId: 230, content: '약한 연무를 동반한 천둥구름' },
  { weatherId: 231, content: '연무를 동반한 천둥구름' },
  { weatherId: 232, content: '강한 안개비를 동반한 천둥구름' },
  { weatherId: 300, content: '가벼운 안개비' },
  { weatherId: 301, content: '안개비' },
  { weatherId: 302, content: '강한 안개비' },
  { weatherId: 310, content: '가벼운 적은비' },
  { weatherId: 311, content: '적은비' },
  { weatherId: 312, content: '강한 적은비' },
  { weatherId: 313, content: '소나기와 안개비' },
  { weatherId: 314, content: '강한 소나기와 안개비' },
  { weatherId: 321, content: '소나기' },
  { weatherId: 500, content: '악한 비' },
  { weatherId: 501, content: '중간 비' },
  { weatherId: 502, content: '강한 비' },
  { weatherId: 503, content: '매우 강한 비' },
  { weatherId: 504, content: '극심한 비' },
  { weatherId: 511, content: '우박' },
  { weatherId: 520, content: '약한 소나기 비' },
  { weatherId: 521, content: '소나기 비' },
  { weatherId: 522, content: '강한 소나기 비' },
  { weatherId: 531, content: '불규칙적 소나기 비' },
  { weatherId: 600, content: '가벼운 눈' },
  { weatherId: 601, content: '눈' },
  { weatherId: 602, content: '강한 눈' },
  { weatherId: 611, content: '진눈깨비' },
  { weatherId: 612, content: '소나기 진눈깨비' },
  { weatherId: 615, content: '약한 비와 눈' },
  { weatherId: 616, content: '비와 눈' },
  { weatherId: 620, content: '약한 소나기 눈' },
  { weatherId: 621, content: '소나기 눈' },
  { weatherId: 622, content: '강한 소나기 눈' },
  { weatherId: 701, content: '박무' },
  { weatherId: 711, content: '연기' },
  { weatherId: 721, content: '연무' },
  { weatherId: 731, content: '모래 먼지' },
  { weatherId: 741, content: '안개' },
  { weatherId: 751, content: '모래' },
  { weatherId: 761, content: '먼지' },
  { weatherId: 762, content: '화산재' },
  { weatherId: 771, content: '돌풍' },
  { weatherId: 781, content: '토네이도' },
  { weatherId: 800, content: '구름 한 점 없는 맑은 하늘' },
  { weatherId: 801, content: '약간의 구름이 낀 하늘' },
  { weatherId: 802, content: '드문드문 구름이 낀 하늘' },
  { weatherId: 803, content: '구름이 거의 없는 하늘' },
  { weatherId: 804, content: '구름으로 뒤덮인 흐린 하늘' },
  { weatherId: 900, content: '토네이도' },
  { weatherId: 901, content: '태풍' },
  { weatherId: 902, content: '허리케인' },
  { weatherId: 903, content: '한랭' },
  { weatherId: 904, content: '고온' },
  { weatherId: 905, content: '바람부는' },
  { weatherId: 906, content: '우박' },
  { weatherId: 951, content: '바람이 거의 없는' },
  { weatherId: 952, content: '약한 바람' },
  { weatherId: 953, content: '부드러운 바람' },
  { weatherId: 954, content: '중간 세기 바람' },
  { weatherId: 955, content: '신선한 바람' },
  { weatherId: 956, content: '센 바람' },
  { weatherId: 957, content: '돌풍에 가까운 센 바람' },
  { weatherId: 958, content: '돌풍' },
  { weatherId: 959, content: '심각한 돌풍' },
  { weatherId: 960, content: '폭풍' },
  { weatherId: 961, content: '강한 폭풍' },
  { weatherId: 962, content: '허리케인' },
]

export default weatherDescKo;